import { PROJECTILE_TYPES as PT, CAMO_PATTERNS as CP, TANK_CLASSES as TC, RARITY as R } from './constants';

const TANKS = [
  { id: 'recruit', name: 'Recruit', class: TC.LIGHT, rarity: 'COMMON', stats: { hp: 800, defense: 15, attack: 80, reloadSpeed: 1.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 50, speed: 8, turnSpeed: 4 }, visual: { bodyLength: 1.6, bodyWidth: 1.0, turretSize: 0.5, barrelLength: 1.2, barrelWidth: 0.08, primaryColor: '#5a7a5a', secondaryColor: '#3a5a3a', camoPattern: CP.FOREST }, cost: 0, unlockLevel: 1 },
  { id: 'scout', name: 'Scout', class: TC.LIGHT, rarity: 'COMMON', stats: { hp: 700, defense: 10, attack: 65, reloadSpeed: 1.2, bulletsPerShot: 1, projectileType: PT.SHELL, range: 45, speed: 10, turnSpeed: 5 }, visual: { bodyLength: 1.4, bodyWidth: 0.9, turretSize: 0.45, barrelLength: 1.0, barrelWidth: 0.07, primaryColor: '#6a8a5a', secondaryColor: '#4a6a3a', camoPattern: CP.FOREST }, cost: 500, unlockLevel: 2 },
  { id: 'speeder', name: 'Speeder', class: TC.LIGHT, rarity: 'COMMON', stats: { hp: 650, defense: 8, attack: 60, reloadSpeed: 1.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 40, speed: 12, turnSpeed: 6 }, visual: { bodyLength: 1.3, bodyWidth: 0.85, turretSize: 0.4, barrelLength: 0.9, barrelWidth: 0.07, primaryColor: '#7a9a6a', secondaryColor: '#5a7a4a', camoPattern: CP.NONE }, cost: 800, unlockLevel: 3 },
  { id: 'phantom', name: 'Phantom', class: TC.LIGHT, rarity: 'RARE', stats: { hp: 750, defense: 12, attack: 75, reloadSpeed: 1.1, bulletsPerShot: 1, projectileType: PT.SHELL, range: 48, speed: 11, turnSpeed: 5.5 }, visual: { bodyLength: 1.5, bodyWidth: 0.95, turretSize: 0.48, barrelLength: 1.1, barrelWidth: 0.08, primaryColor: '#2a2a3a', secondaryColor: '#1a1a2a', camoPattern: CP.DIGITAL }, cost: 1500, unlockLevel: 5 },
  { id: 'dart', name: 'Dart', class: TC.LIGHT, rarity: 'RARE', stats: { hp: 680, defense: 10, attack: 70, reloadSpeed: 0.9, bulletsPerShot: 1, projectileType: PT.SHELL, range: 42, speed: 13, turnSpeed: 6.5 }, visual: { bodyLength: 1.3, bodyWidth: 0.8, turretSize: 0.42, barrelLength: 1.3, barrelWidth: 0.06, primaryColor: '#c0392b', secondaryColor: '#922b21', camoPattern: CP.NONE }, cost: 2000, unlockLevel: 6 },
  { id: 'viper', name: 'Viper', class: TC.LIGHT, rarity: 'SUPER_RARE', stats: { hp: 900, defense: 18, attack: 90, reloadSpeed: 1.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 50, speed: 11, turnSpeed: 5.5 }, visual: { bodyLength: 1.5, bodyWidth: 0.95, turretSize: 0.5, barrelLength: 1.2, barrelWidth: 0.08, primaryColor: '#1a5a1a', secondaryColor: '#0a3a0a', camoPattern: CP.FOREST }, cost: 4000, unlockLevel: 10 },
  { id: 'shadow', name: 'Shadow', class: TC.LIGHT, rarity: 'EPIC', stats: { hp: 950, defense: 20, attack: 100, reloadSpeed: 0.8, bulletsPerShot: 1, projectileType: PT.SHELL, range: 52, speed: 12, turnSpeed: 6 }, visual: { bodyLength: 1.5, bodyWidth: 0.95, turretSize: 0.5, barrelLength: 1.3, barrelWidth: 0.08, primaryColor: '#0a0a1a', secondaryColor: '#050510', camoPattern: CP.DIGITAL }, cost: 8000, unlockLevel: 18 },
  { id: 'soldier', name: 'Soldier', class: TC.MEDIUM, rarity: 'COMMON', stats: { hp: 1200, defense: 30, attack: 120, reloadSpeed: 2.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 55, speed: 6, turnSpeed: 3.5 }, visual: { bodyLength: 1.8, bodyWidth: 1.2, turretSize: 0.6, barrelLength: 1.4, barrelWidth: 0.1, primaryColor: '#5a6a3a', secondaryColor: '#3a4a2a', camoPattern: CP.FOREST }, cost: 1000, unlockLevel: 3 },
  { id: 'warrior', name: 'Warrior', class: TC.MEDIUM, rarity: 'RARE', stats: { hp: 1500, defense: 35, attack: 140, reloadSpeed: 2.2, bulletsPerShot: 1, projectileType: PT.SHELL, range: 58, speed: 5.5, turnSpeed: 3 }, visual: { bodyLength: 1.9, bodyWidth: 1.25, turretSize: 0.65, barrelLength: 1.5, barrelWidth: 0.11, primaryColor: '#4a5a2a', secondaryColor: '#2a3a1a', camoPattern: CP.FOREST }, cost: 2500, unlockLevel: 7 },
  { id: 'guardian', name: 'Guardian', class: TC.MEDIUM, rarity: 'RARE', stats: { hp: 1800, defense: 45, attack: 130, reloadSpeed: 2.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 55, speed: 5, turnSpeed: 2.8 }, visual: { bodyLength: 2.0, bodyWidth: 1.3, turretSize: 0.7, barrelLength: 1.4, barrelWidth: 0.12, primaryColor: '#3a4a5a', secondaryColor: '#2a3a4a', camoPattern: CP.URBAN }, cost: 3500, unlockLevel: 10 },
  { id: 'patriot', name: 'Patriot', class: TC.MEDIUM, rarity: 'SUPER_RARE', stats: { hp: 2000, defense: 50, attack: 160, reloadSpeed: 2.3, bulletsPerShot: 1, projectileType: PT.SHELL, range: 60, speed: 5.5, turnSpeed: 3 }, visual: { bodyLength: 2.0, bodyWidth: 1.3, turretSize: 0.7, barrelLength: 1.6, barrelWidth: 0.12, primaryColor: '#2a3a6a', secondaryColor: '#1a2a5a', camoPattern: CP.DIGITAL }, cost: 6000, unlockLevel: 14 },
  { id: 'centurion', name: 'Centurion', class: TC.MEDIUM, rarity: 'SUPER_RARE', stats: { hp: 2200, defense: 55, attack: 170, reloadSpeed: 2.4, bulletsPerShot: 1, projectileType: PT.SHELL, range: 62, speed: 5, turnSpeed: 2.8 }, visual: { bodyLength: 2.1, bodyWidth: 1.35, turretSize: 0.72, barrelLength: 1.7, barrelWidth: 0.12, primaryColor: '#5a4a2a', secondaryColor: '#3a3a1a', camoPattern: CP.DESERT }, cost: 7500, unlockLevel: 16 },
  { id: 'ironclad', name: 'Ironclad', class: TC.MEDIUM, rarity: 'EPIC', stats: { hp: 2500, defense: 60, attack: 180, reloadSpeed: 2.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 60, speed: 4.5, turnSpeed: 2.5 }, visual: { bodyLength: 2.2, bodyWidth: 1.4, turretSize: 0.75, barrelLength: 1.6, barrelWidth: 0.13, primaryColor: '#4a4a4a', secondaryColor: '#2a2a2a', camoPattern: CP.URBAN }, cost: 10000, unlockLevel: 20 },
  { id: 'crusader', name: 'Crusader', class: TC.MEDIUM, rarity: 'EPIC', stats: { hp: 2800, defense: 65, attack: 200, reloadSpeed: 2.6, bulletsPerShot: 1, projectileType: PT.SHELL, range: 65, speed: 4.5, turnSpeed: 2.5 }, visual: { bodyLength: 2.2, bodyWidth: 1.4, turretSize: 0.78, barrelLength: 1.8, barrelWidth: 0.13, primaryColor: '#8a7a2a', secondaryColor: '#6a5a1a', camoPattern: CP.DESERT }, cost: 14000, unlockLevel: 24 },
  { id: 'titan', name: 'Titan', class: TC.HEAVY, rarity: 'EPIC', stats: { hp: 5000, defense: 85, attack: 350, reloadSpeed: 3.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 60, speed: 3, turnSpeed: 1.5 }, visual: { bodyLength: 2.4, bodyWidth: 1.6, turretSize: 0.9, barrelLength: 2.0, barrelWidth: 0.15, primaryColor: '#2d5a3d', secondaryColor: '#1a3a25', camoPattern: CP.FOREST }, cost: 15000, unlockLevel: 25 },
  { id: 'fortress', name: 'Fortress', class: TC.HEAVY, rarity: 'EPIC', stats: { hp: 5500, defense: 90, attack: 300, reloadSpeed: 3.8, bulletsPerShot: 1, projectileType: PT.SHELL, range: 55, speed: 2.5, turnSpeed: 1.2 }, visual: { bodyLength: 2.6, bodyWidth: 1.7, turretSize: 0.95, barrelLength: 1.8, barrelWidth: 0.16, primaryColor: '#4a4a3a', secondaryColor: '#2a2a1a', camoPattern: CP.URBAN }, cost: 18000, unlockLevel: 28 },
  { id: 'mammoth', name: 'Mammoth', class: TC.HEAVY, rarity: 'MYTHIC', stats: { hp: 6500, defense: 92, attack: 400, reloadSpeed: 4.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 65, speed: 2, turnSpeed: 1 }, visual: { bodyLength: 2.8, bodyWidth: 1.8, turretSize: 1.0, barrelLength: 2.2, barrelWidth: 0.18, primaryColor: '#3a3a2a', secondaryColor: '#1a1a0a', camoPattern: CP.DESERT }, cost: 25000, unlockLevel: 35 },
  { id: 'goliath', name: 'Goliath', class: TC.HEAVY, rarity: 'MYTHIC', stats: { hp: 7000, defense: 95, attack: 450, reloadSpeed: 4.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 70, speed: 1.8, turnSpeed: 0.9 }, visual: { bodyLength: 3.0, bodyWidth: 1.9, turretSize: 1.1, barrelLength: 2.5, barrelWidth: 0.2, primaryColor: '#2a2a2a', secondaryColor: '#0a0a0a', camoPattern: CP.NONE }, cost: 35000, unlockLevel: 40 },
  { id: 'juggernaut', name: 'Juggernaut', class: TC.HEAVY, rarity: 'LEGENDARY', stats: { hp: 8000, defense: 97, attack: 500, reloadSpeed: 5.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 72, speed: 1.5, turnSpeed: 0.8 }, visual: { bodyLength: 3.2, bodyWidth: 2.0, turretSize: 1.2, barrelLength: 2.8, barrelWidth: 0.22, primaryColor: '#1a1a1a', secondaryColor: '#0a0a0a', camoPattern: CP.DIGITAL }, cost: 50000, unlockLevel: 50 },
  { id: 'howitzer', name: 'Howitzer', class: TC.ARTILLERY, rarity: 'RARE', stats: { hp: 1000, defense: 20, attack: 250, reloadSpeed: 4.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 90, speed: 3, turnSpeed: 1.5 }, visual: { bodyLength: 2.0, bodyWidth: 1.3, turretSize: 0.7, barrelLength: 2.5, barrelWidth: 0.14, primaryColor: '#5a5a3a', secondaryColor: '#3a3a1a', camoPattern: CP.DESERT }, cost: 3000, unlockLevel: 8 },
  { id: 'mortar', name: 'Mortar', class: TC.ARTILLERY, rarity: 'SUPER_RARE', stats: { hp: 1100, defense: 22, attack: 300, reloadSpeed: 4.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 100, speed: 2.5, turnSpeed: 1.2 }, visual: { bodyLength: 1.8, bodyWidth: 1.2, turretSize: 0.8, barrelLength: 1.5, barrelWidth: 0.2, primaryColor: '#6a5a2a', secondaryColor: '#4a3a1a', camoPattern: CP.DESERT }, cost: 5000, unlockLevel: 12 },
  { id: 'thunder', name: 'Thunder', class: TC.ARTILLERY, rarity: 'EPIC', stats: { hp: 1300, defense: 25, attack: 400, reloadSpeed: 5.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 110, speed: 2.5, turnSpeed: 1 }, visual: { bodyLength: 2.2, bodyWidth: 1.4, turretSize: 0.85, barrelLength: 3.0, barrelWidth: 0.16, primaryColor: '#3a4a5a', secondaryColor: '#2a3a4a', camoPattern: CP.ARCTIC }, cost: 12000, unlockLevel: 22 },
  { id: 'siege', name: 'Siege', class: TC.ARTILLERY, rarity: 'MYTHIC', stats: { hp: 1500, defense: 28, attack: 500, reloadSpeed: 6.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 120, speed: 2, turnSpeed: 0.8 }, visual: { bodyLength: 2.5, bodyWidth: 1.5, turretSize: 0.9, barrelLength: 3.5, barrelWidth: 0.18, primaryColor: '#4a3a2a', secondaryColor: '#2a1a0a', camoPattern: CP.DESERT }, cost: 20000, unlockLevel: 30 },
  { id: 'devastator', name: 'Devastator', class: TC.ARTILLERY, rarity: 'LEGENDARY', stats: { hp: 1800, defense: 30, attack: 650, reloadSpeed: 7.0, bulletsPerShot: 1, projectileType: PT.SHELL, range: 130, speed: 1.5, turnSpeed: 0.7 }, visual: { bodyLength: 2.8, bodyWidth: 1.6, turretSize: 1.0, barrelLength: 4.0, barrelWidth: 0.2, primaryColor: '#2a1a1a', secondaryColor: '#1a0a0a', camoPattern: CP.LAVA }, cost: 45000, unlockLevel: 48 },
  { id: 'marksman', name: 'Marksman', class: TC.SNIPER, rarity: 'RARE', stats: { hp: 900, defense: 15, attack: 300, reloadSpeed: 3.0, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 100, speed: 4, turnSpeed: 2 }, visual: { bodyLength: 1.8, bodyWidth: 1.0, turretSize: 0.55, barrelLength: 2.8, barrelWidth: 0.06, primaryColor: '#5a6a5a', secondaryColor: '#3a4a3a', camoPattern: CP.FOREST }, cost: 3500, unlockLevel: 9 },
  { id: 'eagle_eye', name: 'Eagle Eye', class: TC.SNIPER, rarity: 'SUPER_RARE', stats: { hp: 950, defense: 18, attack: 380, reloadSpeed: 3.5, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 120, speed: 3.5, turnSpeed: 1.8 }, visual: { bodyLength: 1.9, bodyWidth: 1.05, turretSize: 0.58, barrelLength: 3.2, barrelWidth: 0.06, primaryColor: '#4a5a6a', secondaryColor: '#2a3a4a', camoPattern: CP.ARCTIC }, cost: 5500, unlockLevel: 13 },
  { id: 'railgun', name: 'Railgun', class: TC.SNIPER, rarity: 'EPIC', stats: { hp: 1000, defense: 20, attack: 500, reloadSpeed: 4.0, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 140, speed: 3, turnSpeed: 1.5 }, visual: { bodyLength: 2.0, bodyWidth: 1.1, turretSize: 0.6, barrelLength: 3.8, barrelWidth: 0.07, primaryColor: '#3a3a5a', secondaryColor: '#1a1a3a', camoPattern: CP.DIGITAL }, cost: 13000, unlockLevel: 23 },
  { id: 'piercer', name: 'Piercer', class: TC.SNIPER, rarity: 'MYTHIC', stats: { hp: 1100, defense: 22, attack: 600, reloadSpeed: 4.5, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 150, speed: 2.8, turnSpeed: 1.3 }, visual: { bodyLength: 2.1, bodyWidth: 1.15, turretSize: 0.62, barrelLength: 4.0, barrelWidth: 0.07, primaryColor: '#5a2a3a', secondaryColor: '#3a1a2a', camoPattern: CP.NONE }, cost: 22000, unlockLevel: 32 },
  { id: 'deadeye', name: 'Deadeye', class: TC.SNIPER, rarity: 'LEGENDARY', stats: { hp: 1200, defense: 25, attack: 750, reloadSpeed: 5.0, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 160, speed: 2.5, turnSpeed: 1.2 }, visual: { bodyLength: 2.2, bodyWidth: 1.2, turretSize: 0.65, barrelLength: 4.5, barrelWidth: 0.07, primaryColor: '#1a0a2a', secondaryColor: '#0a0a1a', camoPattern: CP.DIGITAL }, cost: 48000, unlockLevel: 50 },
  { id: 'hellfire', name: 'Hellfire', class: TC.ROCKET, rarity: 'RARE', stats: { hp: 1100, defense: 25, attack: 200, reloadSpeed: 3.0, bulletsPerShot: 2, projectileType: PT.ROCKET, range: 70, speed: 5, turnSpeed: 2.5 }, visual: { bodyLength: 1.9, bodyWidth: 1.2, turretSize: 0.7, barrelLength: 1.5, barrelWidth: 0.12, primaryColor: '#8a2a1a', secondaryColor: '#5a1a0a', camoPattern: CP.LAVA }, cost: 3000, unlockLevel: 8 },
  { id: 'hydra', name: 'Hydra', class: TC.ROCKET, rarity: 'SUPER_RARE', stats: { hp: 1200, defense: 28, attack: 180, reloadSpeed: 2.5, bulletsPerShot: 3, projectileType: PT.ROCKET, range: 65, speed: 4.5, turnSpeed: 2.3 }, visual: { bodyLength: 2.0, bodyWidth: 1.25, turretSize: 0.75, barrelLength: 1.4, barrelWidth: 0.1, primaryColor: '#2a5a2a', secondaryColor: '#1a3a1a', camoPattern: CP.FOREST }, cost: 5500, unlockLevel: 13 },
  { id: 'salamander', name: 'Salamander', class: TC.ROCKET, rarity: 'EPIC', stats: { hp: 1400, defense: 32, attack: 220, reloadSpeed: 2.8, bulletsPerShot: 2, projectileType: PT.ROCKET, range: 75, speed: 4.5, turnSpeed: 2.2 }, visual: { bodyLength: 2.1, bodyWidth: 1.3, turretSize: 0.78, barrelLength: 1.6, barrelWidth: 0.13, primaryColor: '#9a4a0a', secondaryColor: '#6a2a0a', camoPattern: CP.LAVA }, cost: 11000, unlockLevel: 21 },
  { id: 'storm', name: 'Storm', class: TC.ROCKET, rarity: 'MYTHIC', stats: { hp: 1600, defense: 35, attack: 250, reloadSpeed: 2.5, bulletsPerShot: 4, projectileType: PT.ROCKET, range: 80, speed: 4, turnSpeed: 2 }, visual: { bodyLength: 2.2, bodyWidth: 1.35, turretSize: 0.82, barrelLength: 1.5, barrelWidth: 0.11, primaryColor: '#2a3a5a', secondaryColor: '#1a2a4a', camoPattern: CP.ARCTIC }, cost: 24000, unlockLevel: 34 },
  { id: 'apocalypse_rocket', name: 'Annihilator', class: TC.ROCKET, rarity: 'LEGENDARY', stats: { hp: 1800, defense: 38, attack: 280, reloadSpeed: 2.2, bulletsPerShot: 6, projectileType: PT.ROCKET, range: 85, speed: 3.5, turnSpeed: 1.8 }, visual: { bodyLength: 2.4, bodyWidth: 1.4, turretSize: 0.88, barrelLength: 1.6, barrelWidth: 0.12, primaryColor: '#5a0a0a', secondaryColor: '#3a0a0a', camoPattern: CP.LAVA }, cost: 42000, unlockLevel: 45 },
  { id: 'gatling', name: 'Gatling', class: TC.MACHINE_GUN, rarity: 'COMMON', stats: { hp: 1000, defense: 20, attack: 25, reloadSpeed: 0.1, bulletsPerShot: 1, projectileType: PT.BULLET, range: 40, speed: 6, turnSpeed: 3 }, visual: { bodyLength: 1.7, bodyWidth: 1.1, turretSize: 0.6, barrelLength: 1.5, barrelWidth: 0.05, primaryColor: '#5a5a5a', secondaryColor: '#3a3a3a', camoPattern: CP.URBAN }, cost: 1200, unlockLevel: 4 },
  { id: 'minigun', name: 'Minigun', class: TC.MACHINE_GUN, rarity: 'RARE', stats: { hp: 1100, defense: 22, attack: 30, reloadSpeed: 0.08, bulletsPerShot: 1, projectileType: PT.BULLET, range: 45, speed: 5.5, turnSpeed: 2.8 }, visual: { bodyLength: 1.8, bodyWidth: 1.15, turretSize: 0.62, barrelLength: 1.6, barrelWidth: 0.05, primaryColor: '#4a5a4a', secondaryColor: '#2a3a2a', camoPattern: CP.FOREST }, cost: 2800, unlockLevel: 7 },
  { id: 'buzzsaw', name: 'Buzzsaw', class: TC.MACHINE_GUN, rarity: 'SUPER_RARE', stats: { hp: 1300, defense: 25, attack: 35, reloadSpeed: 0.06, bulletsPerShot: 2, projectileType: PT.BULLET, range: 42, speed: 5, turnSpeed: 2.5 }, visual: { bodyLength: 1.9, bodyWidth: 1.2, turretSize: 0.65, barrelLength: 1.4, barrelWidth: 0.06, primaryColor: '#6a4a2a', secondaryColor: '#4a2a1a', camoPattern: CP.DESERT }, cost: 6000, unlockLevel: 14 },
  { id: 'hornet', name: 'Hornet', class: TC.MACHINE_GUN, rarity: 'EPIC', stats: { hp: 1500, defense: 28, attack: 40, reloadSpeed: 0.05, bulletsPerShot: 2, projectileType: PT.BULLET, range: 48, speed: 5.5, turnSpeed: 3 }, visual: { bodyLength: 1.8, bodyWidth: 1.15, turretSize: 0.63, barrelLength: 1.5, barrelWidth: 0.05, primaryColor: '#8a8a1a', secondaryColor: '#5a5a0a', camoPattern: CP.NONE }, cost: 10000, unlockLevel: 19 },
  { id: 'vulcan', name: 'Vulcan', class: TC.MACHINE_GUN, rarity: 'MYTHIC', stats: { hp: 1700, defense: 32, attack: 45, reloadSpeed: 0.04, bulletsPerShot: 3, projectileType: PT.BULLET, range: 50, speed: 5, turnSpeed: 2.8 }, visual: { bodyLength: 2.0, bodyWidth: 1.25, turretSize: 0.68, barrelLength: 1.6, barrelWidth: 0.06, primaryColor: '#3a1a3a', secondaryColor: '#1a0a1a', camoPattern: CP.DIGITAL }, cost: 28000, unlockLevel: 38 },
  { id: 'tesla', name: 'Tesla', class: TC.SPECIAL, rarity: 'EPIC', stats: { hp: 1400, defense: 30, attack: 150, reloadSpeed: 1.5, bulletsPerShot: 1, projectileType: PT.EMP, range: 35, speed: 5, turnSpeed: 3 }, visual: { bodyLength: 1.9, bodyWidth: 1.2, turretSize: 0.7, barrelLength: 1.0, barrelWidth: 0.15, primaryColor: '#1a3a6a', secondaryColor: '#0a2a5a', camoPattern: CP.DIGITAL }, cost: 12000, unlockLevel: 22 },
  { id: 'flamethrower', name: 'Inferno', class: TC.SPECIAL, rarity: 'EPIC', stats: { hp: 1600, defense: 35, attack: 80, reloadSpeed: 0.05, bulletsPerShot: 1, projectileType: PT.FLAME, range: 20, speed: 5.5, turnSpeed: 3 }, visual: { bodyLength: 2.0, bodyWidth: 1.3, turretSize: 0.72, barrelLength: 1.8, barrelWidth: 0.18, primaryColor: '#8a2a0a', secondaryColor: '#5a1a0a', camoPattern: CP.LAVA }, cost: 13000, unlockLevel: 24 },
  { id: 'emp_tank', name: 'Disruptor', class: TC.SPECIAL, rarity: 'MYTHIC', stats: { hp: 1500, defense: 32, attack: 180, reloadSpeed: 3.0, bulletsPerShot: 1, projectileType: PT.EMP, range: 40, speed: 4.5, turnSpeed: 2.5 }, visual: { bodyLength: 2.0, bodyWidth: 1.3, turretSize: 0.75, barrelLength: 1.2, barrelWidth: 0.2, primaryColor: '#0a1a4a', secondaryColor: '#050a2a', camoPattern: CP.DIGITAL }, cost: 20000, unlockLevel: 30 },
  { id: 'laser_tank', name: 'Photon', class: TC.SPECIAL, rarity: 'MYTHIC', stats: { hp: 1300, defense: 28, attack: 200, reloadSpeed: 2.0, bulletsPerShot: 1, projectileType: PT.LASER, range: 80, speed: 4, turnSpeed: 2 }, visual: { bodyLength: 2.1, bodyWidth: 1.25, turretSize: 0.68, barrelLength: 2.5, barrelWidth: 0.08, primaryColor: '#1a4a4a', secondaryColor: '#0a2a2a', camoPattern: CP.OCEAN }, cost: 22000, unlockLevel: 33 },
  { id: 'plasma_cannon', name: 'Nova', class: TC.SPECIAL, rarity: 'LEGENDARY', stats: { hp: 1600, defense: 35, attack: 450, reloadSpeed: 4.0, bulletsPerShot: 1, projectileType: PT.PLASMA, range: 70, speed: 3.5, turnSpeed: 1.8 }, visual: { bodyLength: 2.2, bodyWidth: 1.35, turretSize: 0.8, barrelLength: 2.0, barrelWidth: 0.15, primaryColor: '#4a0a6a', secondaryColor: '#2a0a4a', camoPattern: CP.NONE }, cost: 40000, unlockLevel: 42 },
  { id: 'dragon', name: 'Dragon', class: TC.LEGENDARY, rarity: 'LEGENDARY', stats: { hp: 4000, defense: 70, attack: 350, reloadSpeed: 2.0, bulletsPerShot: 3, projectileType: PT.FLAME, range: 45, speed: 6, turnSpeed: 3 }, visual: { bodyLength: 2.5, bodyWidth: 1.5, turretSize: 0.9, barrelLength: 2.0, barrelWidth: 0.18, primaryColor: '#8a1a0a', secondaryColor: '#5a0a0a', camoPattern: CP.LAVA }, cost: 55000, unlockLevel: 55 },
  { id: 'phoenix', name: 'Phoenix', class: TC.LEGENDARY, rarity: 'LEGENDARY', stats: { hp: 3500, defense: 60, attack: 300, reloadSpeed: 1.8, bulletsPerShot: 2, projectileType: PT.PLASMA, range: 60, speed: 7, turnSpeed: 3.5 }, visual: { bodyLength: 2.3, bodyWidth: 1.4, turretSize: 0.85, barrelLength: 2.2, barrelWidth: 0.14, primaryColor: '#ffa500', secondaryColor: '#cc8400', camoPattern: CP.NONE }, cost: 58000, unlockLevel: 58 },
  { id: 'kraken', name: 'Kraken', class: TC.LEGENDARY, rarity: 'LEGENDARY', stats: { hp: 5000, defense: 80, attack: 280, reloadSpeed: 1.5, bulletsPerShot: 4, projectileType: PT.ROCKET, range: 75, speed: 4, turnSpeed: 2 }, visual: { bodyLength: 2.8, bodyWidth: 1.7, turretSize: 1.0, barrelLength: 1.8, barrelWidth: 0.14, primaryColor: '#0a3a5a', secondaryColor: '#0a2a3a', camoPattern: CP.OCEAN }, cost: 62000, unlockLevel: 62 },
  { id: 'odin', name: 'Odin', class: TC.LEGENDARY, rarity: 'LEGENDARY', stats: { hp: 6000, defense: 88, attack: 500, reloadSpeed: 3.0, bulletsPerShot: 1, projectileType: PT.SNIPER, range: 150, speed: 3, turnSpeed: 1.5 }, visual: { bodyLength: 2.6, bodyWidth: 1.6, turretSize: 0.95, barrelLength: 4.0, barrelWidth: 0.1, primaryColor: '#3a3a5a', secondaryColor: '#1a1a3a', camoPattern: CP.ARCTIC }, cost: 70000, unlockLevel: 70 },
  { id: 'valkyrie', name: 'Valkyrie', class: TC.LEGENDARY, rarity: 'LEGENDARY', stats: { hp: 4500, defense: 72, attack: 320, reloadSpeed: 1.6, bulletsPerShot: 2, projectileType: PT.LASER, range: 90, speed: 6, turnSpeed: 3 }, visual: { bodyLength: 2.4, bodyWidth: 1.45, turretSize: 0.88, barrelLength: 2.8, barrelWidth: 0.09, primaryColor: '#c0c0c0', secondaryColor: '#808080', camoPattern: CP.NONE }, cost: 65000, unlockLevel: 65 },
  { id: 'worldbreaker', name: 'WorldBreaker', class: TC.ULTIMATE, rarity: 'ULTIMATE', stats: { hp: 10000, defense: 98, attack: 800, reloadSpeed: 4.0, bulletsPerShot: 1, projectileType: PT.PLASMA, range: 100, speed: 3, turnSpeed: 1.5 }, visual: { bodyLength: 3.5, bodyWidth: 2.2, turretSize: 1.3, barrelLength: 3.5, barrelWidth: 0.25, primaryColor: '#1a0a0a', secondaryColor: '#0a0505', camoPattern: CP.LAVA }, cost: 150000, unlockLevel: 80 },
  { id: 'apocalypse', name: 'Apocalypse', class: TC.ULTIMATE, rarity: 'ULTIMATE', stats: { hp: 12000, defense: 99, attack: 1000, reloadSpeed: 5.0, bulletsPerShot: 2, projectileType: PT.PLASMA, range: 120, speed: 2.5, turnSpeed: 1 }, visual: { bodyLength: 3.8, bodyWidth: 2.4, turretSize: 1.5, barrelLength: 4.0, barrelWidth: 0.3, primaryColor: '#0a0a0a', secondaryColor: '#050505', camoPattern: CP.NONE }, cost: 300000, unlockLevel: 100 },
  { id: 'wraith', name: 'Wraith', class: TC.LIGHT, rarity: 'MYTHIC', stats: { hp: 1100, defense: 22, attack: 120, reloadSpeed: 0.7, bulletsPerShot: 1, projectileType: PT.SHELL, range: 55, speed: 14, turnSpeed: 7 }, visual: { bodyLength: 1.4, bodyWidth: 0.85, turretSize: 0.45, barrelLength: 1.4, barrelWidth: 0.07, primaryColor: '#2a0a3a', secondaryColor: '#1a0a2a', camoPattern: CP.DIGITAL }, cost: 30000, unlockLevel: 38 },
  { id: 'reaper', name: 'Reaper', class: TC.SPECIAL, rarity: 'LEGENDARY', stats: { hp: 2000, defense: 40, attack: 380, reloadSpeed: 2.5, bulletsPerShot: 1, projectileType: PT.LASER, range: 85, speed: 5, turnSpeed: 2.5 }, visual: { bodyLength: 2.3, bodyWidth: 1.35, turretSize: 0.82, barrelLength: 2.8, barrelWidth: 0.1, primaryColor: '#1a0a0a', secondaryColor: '#0a0505', camoPattern: CP.NONE }, cost: 55000, unlockLevel: 55 },
  { id: 'colossus', name: 'Colossus', class: TC.HEAVY, rarity: 'LEGENDARY', stats: { hp: 9000, defense: 96, attack: 550, reloadSpeed: 5.5, bulletsPerShot: 1, projectileType: PT.SHELL, range: 75, speed: 1.2, turnSpeed: 0.6 }, visual: { bodyLength: 3.4, bodyWidth: 2.1, turretSize: 1.25, barrelLength: 3.0, barrelWidth: 0.24, primaryColor: '#3a2a1a', secondaryColor: '#1a1a0a', camoPattern: CP.DESERT }, cost: 60000, unlockLevel: 60 },
  { id: 'tempest', name: 'Tempest', class: TC.ROCKET, rarity: 'LEGENDARY', stats: { hp: 2000, defense: 40, attack: 300, reloadSpeed: 2.0, bulletsPerShot: 8, projectileType: PT.ROCKET, range: 90, speed: 3.5, turnSpeed: 1.8 }, visual: { bodyLength: 2.5, bodyWidth: 1.45, turretSize: 0.9, barrelLength: 1.8, barrelWidth: 0.13, primaryColor: '#1a2a4a', secondaryColor: '#0a1a3a', camoPattern: CP.OCEAN }, cost: 55000, unlockLevel: 55 },
];

export function getTankById(id) {
  return TANKS.find(t => t.id === id);
}

export function getTanksByClass(tankClass) {
  return TANKS.filter(t => t.class === tankClass);
}

export function getTanksByRarity(rarity) {
  return TANKS.filter(t => t.rarity === rarity);
}

export function getUnlockedTanks(level) {
  return TANKS.filter(t => t.unlockLevel <= level);
}

export function getAffordableTanks(bp, level) {
  return TANKS.filter(t => t.cost <= bp && t.unlockLevel <= level);
}

export default TANKS;
